networks:
  go-tg-bot-network:
    driver: bridge
services:
  postgres:
    container_name: postgres_go_bot
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./docker/volumes/pg_data:/data/postgres:rw
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - go-tg-bot-network

  bot:
    container_name: go_tg_bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env.production
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    networks:
      - go-tg-bot-network